FROM adoptopenjdk/openjdk11:latest
#WORKDIR /app
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENV HOST_DB=""
ENV DATABASE_USER=""
ENV DATABASE_PASSWORD=""
ENV DATABASE_NAME=""

EXPOSE 8080

ENTRYPOINT ["java","-jar", "app.jar"]
#"-DHOST_DB=$HOST_DB", "-DDATABASE_USER=$DATABASE_USER", "-DDATABASE_PASSWORD=$DATABASE_PASSWORD", "-DDATABASE_NAME=$DATABASE_NAME",
